# Generated by Django 4.0.3 on 2022-03-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
